[project]
name = "kitchai-sigr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "libsql-client>=0.3.0",
    "python-dotenv>=1.0.0",
]

[tool.uv.workspace]
members = [
    "app",
]
